/* Generated By:JavaCC: Do not edit this line. MiniJavaTreeConstants.java Version 5.0 */
public interface MiniJavaTreeConstants
{
  public int JJTSTART = 0;
  public int JJTMAINCLASS = 1;
  public int JJTCLASSDECLARATION = 2;
  public int JJTVARDECLARATION = 3;
  public int JJTMETHODDECLARATION = 4;
  public int JJTRETURNEXPRESSION = 5;
  public int JJTTYPE = 6;
  public int JJTVOID = 7;
  public int JJTASSIGNMENT = 8;
  public int JJTARRAYASSIGNMENT = 9;
  public int JJTASSIGNMENTOPERATOR = 10;
  public int JJTIFSTATEMENT = 11;
  public int JJTWHILESTATEMENT = 12;
  public int JJTPRINTSTATEMENT = 13;
  public int JJTRELATIONALEXPRESSION = 14;
  public int JJTRELATIONALOPERATOR = 15;
  public int JJTARRAYEXPRESSION = 16;
  public int JJTCALLNODE = 17;
  public int JJTADDNODE = 18;
  public int JJTMULTINODE = 19;
  public int JJTLENGTHNODE = 20;
  public int JJTNEWCLASSNODE = 21;
  public int JJTNEWINTARRAYNODE = 22;
  public int JJTNEGNODE = 23;
  public int JJTTHISNODE = 24;
  public int JJTINTCONSTNODE = 25;
  public int JJTTRUENODE = 26;
  public int JJTFALSENODE = 27;
  public int JJTEXPLIST = 28;
  public int JJTIDENTIFIER = 29;


  public String[] jjtNodeName = {
    "Start",
    "MainClass",
    "ClassDeclaration",
    "VarDeclaration",
    "MethodDeclaration",
    "ReturnExpression",
    "Type",
    "void",
    "Assignment",
    "ArrayAssignment",
    "AssignmentOperator",
    "IfStatement",
    "WhileStatement",
    "PrintStatement",
    "RelationalExpression",
    "RelationalOperator",
    "ArrayExpression",
    "CallNode",
    "AddNode",
    "MultiNode",
    "LengthNode",
    "NewClassNode",
    "NewIntArrayNode",
    "NegNode",
    "ThisNode",
    "IntConstNode",
    "TrueNode",
    "FalseNode",
    "ExpList",
    "Identifier",
  };
}
/* JavaCC - OriginalChecksum=e60c4083dceebfc605761c404ccc1bd9 (do not edit this line) */
